# Travis CI configuration file.

language: php

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5

sudo: false

matrix:
  include:
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
    - composer install
    - >
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." || $TRAVIS_PHP_VERSION == nightly ]]; then
        export PATH="$(pwd)/vendor/bin:$PATH"
        composer require "phpunit/phpunit=^5.7.15" --no-suggest --no-scripts
      fi

script:
    - phpunit
